// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlUitAQ_hDTk_EhmmAP1-fbn8h6KRr8Jo',
    appId: '1:1062805760329:android:15a772c886c0dd425e9298',
    messagingSenderId: '1062805760329',
    projectId: 'bird-2a331',
    databaseURL: 'https://bird-2a331-default-rtdb.firebaseio.com',
    storageBucket: 'bird-2a331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx1K8vzcXZHxOP0jm_qFQPg8iTnDK93gY',
    appId: '1:1062805760329:ios:5db3a538e4339cc85e9298',
    messagingSenderId: '1062805760329',
    projectId: 'bird-2a331',
    databaseURL: 'https://bird-2a331-default-rtdb.firebaseio.com',
    storageBucket: 'bird-2a331.firebasestorage.app',
    androidClientId: '1062805760329-21h3vboi0kei20bljdrhj2lv9u2ps173.apps.googleusercontent.com',
    iosClientId: '1062805760329-rt76ic1fu3ghjkljc1rt4q03gbk23ptl.apps.googleusercontent.com',
    iosBundleId: 'com.bird.app',
  );

}